name: vocab-trainer

services:
  postgres:
    image: postgres:15
    container_name: vocab-trainer-postgres
    restart: always
    environment:
      POSTGRES_USER: vocab_trainer
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: vocab_trainer
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: vocab-trainer-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - postgres

volumes:
  postgres_data: