export enum NSGeminiAction {
  DEFINE_WORD = "DEFINE_WORD",
  GENERATE_FLASHCARD = "GENERATE_FLASHCARD",
  GENERATE_TEXT = "GENERATE_TEXT",
  GENERATE_IMAGE = "GENERATE_IMAGE",
  GENERATE_WRONG_ANSWERS = "GENERATE_WRONG_ANSWERS",
}

export enum NSGeminiResetType {
  DAILY_PACIFIC_TIME = "DAILY_PACIFIC_TIME",
}
